import { NextRequest, NextResponse } from "next/server";
import { generatePptxBuffer } from "@/lib/exportPptx";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const title = searchParams.get("title") || "VoiceDeck AI Presentation";
    const subtitle = searchParams.get("subtitle") || "Generated by VoiceDeck AI";
    const slidesJson = searchParams.get("slides");

    let slides = [];
    if (slidesJson) {
      try {
        slides = JSON.parse(slidesJson);
      } catch (e) {
        console.error("Failed to parse slides JSON from searchParams:", e);
      }
    }

    // Default fallback slide if empty
    if (!slides || slides.length === 0) {
      slides = [
        {
          id: 1,
          title: "VoiceDeck AI Executive Overview",
          subtitle: "AI Speech-to-Slide Synthesis & Web3 Micropayments",
          bullets: [
            "Instant conversion of spoken audio transcripts into structured slide decks.",
            "Powered by Gemini 2.5 LLM models for high-accuracy content synthesis.",
            "x402 Protocol integration for seamless Algorand TestNet micropayments.",
            "Professional PowerPoint export featuring Times New Roman typography and slide reference graphics."
          ],
          speakerNotes: "Welcome to VoiceDeck AI presentation deck.",
          icon: "🎤",
          gradient: "from-purple-500 to-blue-600"
        }
      ];
    }

    const buffer = await generatePptxBuffer(slides, title, subtitle);

    const safeName = title
      .replace(/[^a-z0-9]/gi, "_")
      .replace(/_+/g, "_")
      .toLowerCase();

    return new Response(buffer as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${safeName}.pptx"`,
        "Cache-Control": "no-store, max-age=0",
      },
    });
  } catch (error: any) {
    console.error("API Export PPTX Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PPTX" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { slides, title, subtitle } = body;

    const buffer = await generatePptxBuffer(slides || [], title, subtitle);

    const safeName = (title || "VoiceDeck_Presentation")
      .replace(/[^a-z0-9]/gi, "_")
      .replace(/_+/g, "_")
      .toLowerCase();

    return new Response(buffer as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${safeName}.pptx"`,
      },
    });
  } catch (error: any) {
    console.error("API Export PPTX POST Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PPTX" },
      { status: 500 }
    );
  }
}
